# Generated by Django 3.0.2 on 2020-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=25)),
                ('assignment_link', models.URLField()),
                ('due_date', models.DateField()),
                ('dropbox', models.URLField()),
            ],
        ),
    ]
