# Generated by Django 3.0.2 on 2020-06-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': 'Assignments'},
        ),
    ]
