# Generated by Django 3.0.2 on 2020-06-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20200616_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(default='Description', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL Path to access this page.', max_length=200),
        ),
    ]
